name: Release

on:
  release:
    types: [created]

jobs:
  publish-cli:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: macos-12
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "name=release_version::$RELEASE_VERSION"  >> $GITHUB_OUTPUT
      - name: Assemble Components
        run: |
          chmod +x ./hack/build.sh
          ./hack/build.sh
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.release_version }}
          GITHUB_OWNER: ${{ github.repository_owner }}
      - name: Save release assets
        uses: softprops/action-gh-release@v1
        with:
          files: release/*