name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests-full:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: get_version
        run: |
          RELEASE_VERSION=$(echo $GITHUB_REF | sed -nE 's!refs/tags/!!p')
          echo "::set-output name=release_version::$RELEASE_VERSION"
      - name: Assemble Components
        run: |
          chmod +x ./hack/build.sh
          ./hack/build.sh
        env:
          RELEASE_VERSION: ${{ steps.get_version.outputs.release_version }}
          GITHUB_OWNER: ${{ github.repository_owner }}
